"""create tables

Revision ID: 4907299b90ba
Revises: 
Create Date: 2026-05-19 21:34:40.813467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4907299b90ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('middlename', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('passport_serial', sa.String(length=20), nullable=False),
    sa.Column('passport_number', sa.String(length=20), nullable=False),
    sa.Column('passport_issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('passport_issuer', sa.String(length=255), nullable=False),
    sa.Column('passport_code', sa.String(length=20), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('inn', sa.String(length=255), nullable=False),
    sa.Column('ogrnip', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='main_api'
    )
    op.create_table('calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('insurance_company_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('sts_id', sa.Integer(), nullable=False),
    sa.Column('policy_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('policy_start_date', sa.Date(), nullable=False),
    sa.Column('use_period', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['main_api.agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='main_api'
    )
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['main_api.agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='main_api'
    )
    op.create_table('commissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('insurance_company_id', sa.Integer(), nullable=False),
    sa.Column('calculation_id', sa.Integer(), nullable=False),
    sa.Column('policy_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('percent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['main_api.agents.id'], ),
    sa.ForeignKeyConstraint(['calculation_id'], ['main_api.calculations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='main_api'
    )
    op.create_table('payout_commissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payout_id', sa.Integer(), nullable=False),
    sa.Column('commission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commission_id'], ['main_api.commissions.id'], ),
    sa.ForeignKeyConstraint(['payout_id'], ['main_api.payouts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='main_api'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payout_commissions', schema='main_api')
    op.drop_table('commissions', schema='main_api')
    op.drop_table('payouts', schema='main_api')
    op.drop_table('calculations', schema='main_api')
    op.drop_table('agents', schema='main_api')
    # ### end Alembic commands ###
