"""delete sts_id

Revision ID: 80306d18e83f
Revises: 4907299b90ba
Create Date: 2026-05-21 10:02:37.772394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80306d18e83f'
down_revision: Union[str, Sequence[str], None] = '4907299b90ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calculations', 'insurance_company_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='main_api')
    op.alter_column('calculations', 'policy_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               schema='main_api')
    op.drop_column('calculations', 'sts_id', schema='main_api')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculations', sa.Column('sts_id', sa.INTEGER(), autoincrement=False, nullable=False), schema='main_api')
    op.alter_column('calculations', 'policy_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               schema='main_api')
    op.alter_column('calculations', 'insurance_company_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='main_api')
    # ### end Alembic commands ###
