"""init calculation companies

Revision ID: c7a8dec6ff13
Revises: 80306d18e83f
Create Date: 2026-05-21 15:27:13.762858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a8dec6ff13'
down_revision: Union[str, Sequence[str], None] = '80306d18e83f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('calculation_id', sa.Integer(), nullable=False),
    sa.Column('insurance_company_id', sa.Integer(), nullable=True),
    sa.Column('policy_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['main_api.agents.id'], ),
    sa.ForeignKeyConstraint(['calculation_id'], ['main_api.calculations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='main_api'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculation_companies', schema='main_api')
    # ### end Alembic commands ###
