"""change payout model

Revision ID: d8548c785438
Revises: c7a8dec6ff13
Create Date: 2026-05-22 11:58:16.460904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8548c785438'
down_revision: Union[str, Sequence[str], None] = 'c7a8dec6ff13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payouts', 'paid_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema='main_api')
    op.drop_column('payouts', 'created_at', schema='main_api')
    op.drop_column('payouts', 'status', schema='main_api')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payouts', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False), schema='main_api')
    op.add_column('payouts', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False), schema='main_api')
    op.alter_column('payouts', 'paid_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema='main_api')
    # ### end Alembic commands ###
